version: '2'

services:
  flask-app:
    build:
      context: ./
    image: flask-app
    ports:
      - "8000:8080"
    volumes:
      - ./app.py:/app/app.py
      - ./load_db.py:/app/load_db.py
    environment:
      - DEBUG=True
    command: ["sh", "-c", "python load_db.py & python app.py"]
    depends_on:
      - mysql-db 

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Password123.
      MYSQL_DATABASE: odb
      MYSQL_USER: user
      MYSQL_PASSWORD: Password123.
