version: '2'

services:
  flask-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: flask-app
    ports:
      - "8000:8000"
    volumes:
      - ./app.py:/app/app.py
    #  - ./load_db.py:/app/load_db.py
    environment:
      - DEBUG=True
    command: ["sh", "-c", "python app.py"]
    depends_on:
      - mssql-db
  
  mssql-db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

